services:
  tidb-sync:
    container_name: tidb-sync
    image: hub.sinoeyes.com/data-technology/tidb-sync:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=local
      # DataX 任务结束后继续下一个任务的时间间隔, 单位: 毫秒
      - SCHEDULED_DATAX_TASK_FIXEDDELAY=5000
      # DataX 任务结束后继续下一个任务的时间间隔, 单位: 毫秒
      - SCHEDULED_DATAX_TASK_JOBPATH=/app/datax/job
    volumes:
      - ./logs:/app/logs
      - ./job:/app/datax/job
      - ./config:/app/config
    restart: no
    network_mode: bridge